### ISSUE TITLE
Post-run `mv` operation fails with unusual error

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-runner#43]
When running [this action](https://github.com/opensafely/households-research/blob/1b1ade40613af2242810d256dc749e076a3b5db7/project.yaml#L28-L34)

```yaml
household_analysis:
    run: jupyter:latest jupyter nbconvert /workspace/analysis/opensafely_age_hh.ipynb --execute --to html --output-dir=/workspace --ExecutePreprocessor.timeout=86400
    needs: [prepare_data]
    outputs:
      moderately_sensitive:
        notebook: opensafely_age_hh.html
        log: analysis/opensafely_age_hh.log
```

We have seen, I believe non-deterministically, it ending with the cryptic `mv: cannot create regular file '/e/FILESFORL3/tpp-https-github-com-opensafely-households-research-master-full-households/household_analysis/log/analysis/opensafely_age_hh.log': No such file or directory` (full log below).

This is cryptic because the code path should work (the logs show it worked for the HTML output immediately prior) but also because it's a strange message from the `mv` command.  If, say, folders were missing (they're not...) you'd get `mv: cannot move`, not `mv: cannot create regular file`.

```
job-runner_1  | 2020-10-14 11:26:03,127 DEBUG       job#312    Looking for outputs to copy to storage at /e/high_privacy/tmp2q8u__id/opensafely_age_hh.html
job-runner_1  | 2020-10-14 11:26:03,436 INFO        job#312    Copied output to /e/FILESFORL3/tpp-https-github-com-opensafely-households-research-master-full-households/household_analysis/notebook/opensafely_age_hh.html
job-runner_1  | 2020-10-14 11:26:03,436 DEBUG       job#312    Looking for outputs to copy to storage at /e/high_privacy/tmp2q8u__id/analysis/opensafely_age_hh.log
job-runner_1  | mv: cannot create regular file '/e/FILESFORL3/tpp-https-github-com-opensafely-households-research-master-full-households/household_analysis/log/analysis/opensafely_age_hh.log': No such file or directory
job-runner_1  | 2020-10-14 11:26:03,475 INFO        job#312    Started pebble's `add_done_callback`
job-runner_1  | 2020-10-14 11:26:03,695 INFO        job#312    Reported error 99 (unclassified) to job server
job-runner_1  | 2020-10-14 11:26:03,695 ERROR       job#312    Command '['mv', '/e/high_privacy/tmp2q8u__id/analysis/opensafely_age_hh.log', '/e/FILESFORL3/tpp-https-github-com-opensafely-households-research-master-full-households/household_analysis/log/analysis/opensafely_age_hh.log']' returned non-zero exit status 1.
job-runner_1  | pebble.common.RemoteTraceback: Traceback (most recent call last):
job-runner_1  |   File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pebble/common.py", line 174, in process_execute
job-runner_1  |     return function(*args, **kwargs)
job-runner_1  |   File "/app/jobrunner/job.py", line 90, in __call__
job-runner_1  |     return self.main()
job-runner_1  |   File "/app/jobrunner/job.py", line 139, in main
job-runner_1  |     self.run_job_and_dependencies(all_jobs=all_jobs)
job-runner_1  |   File "/app/jobrunner/job.py", line 123, in run_job_and_dependencies
job-runner_1  |     self.invoke_docker(prepared_job)
job-runner_1  |   File "/app/jobrunner/job.py", line 236, in invoke_docker
job-runner_1  |     subprocess.check_call(["mv", source_path, target_path])
job-runner_1  |   File "/root/.pyenv/versions/3.8.3/lib/python3.8/subprocess.py", line 364, in check_call
job-runner_1  |     raise CalledProcessError(retcode, cmd)
job-runner_1  | subprocess.CalledProcessError: Command '['mv', '/e/high_privacy/tmp2q8u__id/analysis/opensafely_age_hh.log', '/e/FILESFORL3/tpp-https-github-com-opensafely-households-research-master-full-households/household_analysis/log/analysis/opensafely_age_hh.log']' returned non-zero exit status 1

**Comment by sebbacon** [comment]
Ah - I thin kit's a permissions thing. It seems that somehow we've not ended up with read permissions on a previously-created file at that location.

**Comment by sebbacon** [comment]
However, I don't understand how that could've happened.

I changed the output key per the linked commit above, and re-ran, and everything worked as expected.

So it feels like it could be a non-determinstic issue related to the filesystem

**Comment by bloodearnest** [comment]
Seen this when trying to rm -rf temporary directories in /e/high-privacy - the rm deletes most things, but leaves a file around which I don't have permissions to delete. Windows won't tell me who owns the file.

I think we need to figure out what user the job-runner docker is writing as

**Comment by sebbacon** [comment]
Closing this in the hope we'll remember it exists and re-open it if we see again!
