### ISSUE TITLE
DATABASE_URL not discoverable in live environment 

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-runner#50]
We see this in the docker logs on the TPP server - since, I think, #48 
 
```
job-runner_1  | 2020-10-18 16:22:21,658 INFO        job#374    Running subdocker cmd `docker run --name tpp-https-github-com-opensafely-carehomes-research-master-full-carehomes-generate-cohort --rm --log-driver none -a stdout -a stderr --volume /e/high_privacy/tmp2l3lsm2i:/workspace -e DATABASE_URL=mssql+pyodbc://xx:xxx@192.168.201.1/OPENCorona?driver=ODBC+Driver+17+for+SQL+Server -e TEMP_DATABASE_NAME=OPENCoronaTempTables docker.opensafely.org/cohortextractor:latest generate_cohort --output-dir=/workspace --output-dir=/workspace/output` in /e/high_privacy/tmp2l3lsm2i
job-runner_1  | 2020-10-18 16:22:26,161 INFO        job#374    Started pebble's `add_done_callback`
job-runner_1  | 2020-10-18 16:22:26,438 INFO        job#374    Reported error 2 (usage: cohortextractor [-h] [--version]
job-runner_1  |                        {generate_cohort,generate_measures,cohort_report,notebook,update_codelists,dump_cohort_sql,dump_study_yaml,remote}
job-runner_1  |                        ...
job-runner_1  | cohortextractor: error: generate_cohort: error: one of the arguments --expectations-population --database-url is required
job-runner_1  |  id job#374) to job server
job-runner_1  | 2020-10-18 16:22:26,439 ERROR       job#374    usage: cohortextractor [-h] [--version]
job-runner_1  |                        {generate_cohort,generate_measures,cohort_report,notebook,update_codelists,dump_cohort_sql,dump_study_yaml,remote}
job-runner_1  |                        ...
job-runner_1  | cohortextractor: error: generate_cohort: error: one of the arguments --expectations-population --database-url is required
job-runner_1  | Traceback (most recent call last):
job-runner_1  |   File "/app/jobrunner/main.py", line 33, in report_result
job-runner_1  |     jobs = future.result()
job-runner_1  |   File "/root/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/_base.py", line 432, in result
job-runner_1  |     return self.__get_result()
job-runner_1  |   File "/root/.pyenv/versions/3.8.1/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
job-runner_1  |     raise self._exception
job-runner_1  | jobrunner.exceptions.DockerRunError: usage: cohortextractor [-h] [--version]
job-runner_1  |                        {generate_cohort,generate_measures,cohort_report,notebook,update_codelists,dump_cohort_sql,dump_study_yaml,remote}
job-runner_1  |                        ...
job-runner_1  | cohortextractor: error: generate_cohort: error: one of the arguments --expectations-population --database-url is required
```

It's hard to make sense of this, because the variable *is* set when I start a Python interpreter using the same docker invocation:

```
$ docker run -it --entrypoint bash --name tpp-https-github-com-opensafely-carehomes-research-master-full-carehomes-gene
rate-cohort --rm --log-driver none -a stdout -a stderr --volume //e/high_privacy/tmpz64r8q7i:/workspace -e DATABASE_URL
=mssql+pyodbc://xx:xxxx5@192.168.201.1/OPENCorona?driver=ODBC+Driver+17+for+SQL+Server -e TEMP_DATABA
SE_NAME=OPENCoronaTempTables docker.opensafely.org/cohortextractor:latest
root@4067aaff181d:/workspace# python
Python 3.7.8 (default, Oct  1 2020, 12:13:00)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ.get("DATABASE_URL")
'mssql+pyodbc://xx:xxxxxx@192.168.201.1/OPENCorona?driver=ODBC+Driver+17+for+SQL+Server'
```

**Comment by evansd** [comment]
Closed by #51
