### ISSUE TITLE
Job runner quit unexpectedly

### ISSUE THREAD

**Issue by sebbacon** [opensafely/job-runner#75]
The tail of the log was like this, but with the final `Input/output error` bit repeated very many times, with a different tmp folder name each time (e.g. `/e/high_privacy/tmptaxzsdru`):

```
2020-11-19 18:34:58,008 ERROR       job#749    'action_id'
pebble.common.RemoteTraceback: Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/app/jobrunner/job.py", line 209, in __call__
    return self.main()
  File "/app/jobrunner/job.py", line 258, in main
    self.run_job_and_dependencies(all_jobs=all_jobs)
  File "/app/jobrunner/job.py", line 215, in run_job_and_dependencies
    prepared_job = parse_project_yaml(self.workdir, self.job_spec)
  File "/app/jobrunner/project.py", line 334, in parse_project_yaml
    requested_action_id = job_spec["action_id"]
KeyError: 'action_id'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/jobrunner/main.py", line 33, in report_result
    jobs = future.result()
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: 'action_id'
Exception ignored in: <finalize object at 0x7f44805fbb50; dead>
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/tempfile.py", line 818, in _cleanup
    cls._rmtree(name)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/tempfile.py", line 814, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/shutil.py", line 706, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/shutil.py", line 704, in rmtree
    orig_st = os.lstat(path)
OSError: [Errno 5] Input/output error: '/e/high_privacy/tmptaxzsdru'
```

**Comment by sebbacon** [comment]
The main `action_id` key error is also repeating

**Comment by evansd** [comment]
KeyError fixed by https://github.com/opensafely/job-server/pull/221

Not sure of the source of the `Input/output error` but going to put it down to the job-runner being stuck in a tight error loop combined with a known flaky filesystem – unless it reoccurs.
